cars = [
    :"Akuma",
    :"Bagger",
    :"Bati 801",
    :"Bati 801RR",
    :"Carbon RS",
    :"Daemon",
    :"Double T",
    :"Enduro",
    :"Faggio",
    :"Hakuchou",
    :"Hexer",
    :"Innovation",
    :"Lectro",
    :"Nemesis",
    :"PCJ 600",
    :"Ruffian",
    :"Sanchez",
    :"Sovereign",
    :"Thrust",
    :"Vader",
    :"Blista",
    :"Dilettante",
    :"Issi",
    :"Panto",
    :"Prairie",
    :"Rhapsody",
    :"Cognoscenti Cabrio",
    :"Exemplar",
    :"F620",
    :"Felon",
    :"Felon GT",
    :"Jackal",
    :"Oracle",
    :"Sentinel",
    :"Sentinel XS",
    :"Zion",
    :"Zion Cabrio",
    :"Asea",
    :"Asterope",
    :"Emperor",
    :"Fugitive",
    :"Glendale",
    :"Ingot",
    :"Intruder",
    :"Premier",
    :"Primo",
    :"Regina",
    :"Romero Hearse",
    :"Schafter",
    :"Stanier",
    :"Stratum",
    :"Stretch",
    :"Super Diamond",
    :"Surge",
    :"Tailgater",
    :"Warrener",
    :"Washington",
    :"9F",
    :"9F Cabrio",
    :"Alpha",
    :"Banshee",
    :"Blista Compact",
    :"Buffalo",
    :"Buffalo S",
    :"Carbonizzare",
    :"Comet",
    :"Coquette",
    :"Elegy RH8",
    :"Feltzer",
    :"Furore GT",
    :"Fusilade",
    :"Futo",
    :"Go Go Monkey Blista",
    :"Jester",
    :"Jester (Racecar)",
    :"Kuruma",
    :"Massacro",
    :"Massacro (Racecar)",
    :"Penumbra",
    :"Rapid GT",
    :"Schwartzer",
    :"Sultan",
    :"Surano",
    :"Casco",
    :"Coquette Classic",
    :"JB 700",
    :"Manana",
    :"Monroe",
    :"Peyote",
    :"Pigalle",
    :"Roosevelt",
    :"Stinger",
    :"Stinger GT",
    :"Tornado",
    :"Z-Type",
    :"Adder",
    :"Bullet",
    :"Cheetah",
    :"Entity XF",
    :"Infernus",
    :"Turismo R",
    :"Vacca",
    :"Voltic",
    :"Zentorno",
    :"Blade",
    :"Buccaneer",
    :"Dominator",
    :"Dukes",
    :"Gauntlet",
    :"Hotknife",
    :"Phoenix",
    :"Picador",
    :"Rat-Loader",
    :"Rat-Truck",
    :"Ruiner",
    :"Sabre Turbo",
    :"Slamvan",
    :"Stallion",
    :"Vigero",
    :"Voodoo",
    :"Bifta",
    :"Blazer",
    :"Blazer Lifeguard",
    :"Bodhi",
    :"Dubsta 6x6",
    :"Dune Buggy",
    :"Duneloader",
    :"Hot Rod Blazer",
    :"Injection",
    :"Insurgent",
    :"Kalahari",
    :"Marshall",
    :"Mesa",
    :"Rancher XL",
    :"Rebel",
    :"Sandking SWB",
    :"Sandking XL",
    :"Technical",
    :"The Liberator",
    :"Baller",
    :"BeeJay XL",
    :"Cavalcade",
    :"Dubsta",
    :"FQ 2",
    :"Granger",
    :"Gresley",
    :"Habanero",
    :"Huntley S",
    :"Landstalker",
    :"Mesa",
    :"Patriot",
    :"Radius",
    :"Rocoto",
    :"Seminole",
    :"Serrano",
    :"Bison",
    :"Bobcat",
    :"Boxville",
    :"Burrito",
    :"Camper",
    :"Gang Burrito",
    :"Journey",
    :"Minivan",
    :"Paradise",
    :"Pony",
    :"Rumpo",
    :"Speedo",
    :"Surfer",
    :"Taco Van",
    :"Youga",
    :"BMX",
    :"Cruiser",
    :"Endurex Race Bike",
    :"Fixter",
    :"Scorcher",
    :"Tri-Cycles Race Bike",
    :"Whippet Race Bike"
]
car_colours = [
    :Red,
    :Blue,
    :Pink,
    :Purple,
    :Black,
    :White,
    :Grey,
    :Yellow,
    :Orange,
    :Green,
    :Metal
]
car_colour_finishes = [
    :Standard,
    :Matte,
    :Metallic,
    :Metal,
    :Pearlescent
]

apartments = [
    :"0112 South Rockford Drive, Apartment 13 - $80,000 (Rockford Hills)",
    :"2057 Vespucci Boulevard. Apartment 1 - $87,000 (Little Seoul)",
    :"1115 Boulevard Del Perro, Apartment 18 - $93,000 (Del Perro)",
    :"1561 San Vitas Street, Apartment 2 - $99,000 (West Vinewood)",
    :"1237 Prosperity Street, Apartment 21 - $105,000 (Del Perro, Morningwood)",
    :"0069 Cougar Avenue, Apartment 19 - $112,000 (Vespucci)",
    :"2143 Las Lagunas Boulevard - $115,000 (Hawick)",
    :"1893 Grapeseed Avenue - $118,000 (Sandy Shores)",
    :"140 Zancudo Avenue - $120,000 (Sandy Shores)",
    :"0232 Paleto Boulevard - $121,000 (Paleto Bay)",
    :"The Royale, Apartment 19 - $125,000 (West Vinewood)",
    :"0604 Las Lagunas Boulevard, Apartment 4 - $126,00 (Downtown Vinewood)",
    :"0605 Spanish Avenue, Apartment 1 - $128,000 (Downtown Vinewood)",
    :"1162 Power Street, Apartment 3 - $130,000 (Hawick)",
    :"Dream Tower, Apartment 15 - $134,000 (Dream Tower)",
    :"0325 South Rockford Drive - $137,000 (Little Seoul/Vespucci)",
    :"0504 South Mo Milton Drive - $141,000 (West Vinewood)",
    :"12 Sustancia Road - $143,000 (Palomino Highlands)",
    :"0184 Milton Road Apartment 13 - $146,000 (West Vinewood)",
    :"0115 Bay City Avenue, Apartment 45 - $150,000 (Puerto Del Sol)",
    :"4401 Procopio Drive - $165,000 (Paleto Bay)",
    :"4584 Procopio Drive - $155,000 (Paleto Bay)",
    :"4 Hangman Ave - $175,000 (Vinewood Hills)",
    :"Del Perro Heights, Apartment 7 - $200,000 (Del Perro)",
    :"Del Perro Heights, Apartment 20 - $205,000 (Del Perro)",
    :"3 Alta Street, Apartment. 10 - $217,000 (Downtown Los Santos)",
    :"3 Alta Street, Apartment 57 - $223,000 (Downtown Los Santos)",
    :"4 Integrity Way, Apartment 30 - $235,000 (Downtown Los Santos)",
    :"Richards Majestic, Apartment 4 - $241,000 (Rockford Hills)",
    :"4 Integrity Way, Apartment 35 - $247,000 (Downtown Los Santos)",
    :"Richards Majestic, Apartment 51 - $253,000 (Rockford Hills)",
    :"Tinsel Towers, Apartment 45 - $270,000 (Rockford Hills)",
    :"Tinsel Towers, Apartment 29 - $286,000 (Rockford Hills)",
    :"Weazel Plaza, Apartment 26 - $304,000 (Rockford Hills)",
    :"Weazel Plaza, Apartment 70 - $319,000 (Rockford Hills)",
    :"Weazel Plaza, Apartment 101 - $335,000 (Rockford Hills)",
    :"Eclipse Towers, Apartment 9 - $373,000 (Rockford Hills)",
    :"Eclipse Towers, Apartment 5 - $382,000 (Rockford Hills)",
    :"Eclipse Towers, Apartment 40 - $391,000 (Rockford Hills)",
    :"Eclipse Towers, Apartment 31 - $400,000 (Rockford Hills)",
    :"Del Perro Heights, Apartment 4 - $468,000 (Del Perro)",
    :"4 Integrity Way, Apartment 28 - $476,000 (Downtown Los Santos)",
    :"Richards Majestic, Apartment 2 - $484,000 (Rockford Hills)",
    :"Tinsel Towers, Apartment 42 - $492,000 (Rockford Hills)",
    :"Eclipse Towers, Apartment 3 - $500,000 (Rockford Hills)"
]

head = [
    :Beanie,
    :"Canvas Hat",
    :"Army Cap",
    :"Cap (forwards)",
    :"Cap (backwards)",
    :"Flatcap",
    :"Trilby",
    :"Top Hat",
    :"Bowler Hat",
    :"Pork Pie",
    :"Fedora",
    :"Cowboy Hat",
    :Bandana,
    :"Beat-off Headphones",
    :"Ear Defenders",
    :"Open-Face helmet",
    :"Dirt Bike helmet",
    :"Closed-Face helmet",
    :"Flight Cap",
    :"Bulletproof Helmet",
    :"Monster mask",
    :"Cat mask",
    :"Owl mask",
    :"T-shirt mask",
    :"Gas mask",
    :"Stealth bandana",
    :"Tape mask",
    :"No hat/helmet",
    :"No hat/helmet",
    :"No hat/helmet",
    :"No hat/helmet",
    :"No hat/helmet"
]

chest = [
    :"Suit Jacket with shirt and tie",
    :"Suit Jacket with shirt and bowtie",
    :"Suit Jacket with vest and tie",
    :"Suit Jacket with vest and bowtie",
    :"Suit Jacket with vest",
    :"Vest and tie",
    :"Vest and bowtie",
    :"Vest",
    :"Leather Jacket",
    :"Tracksuit Jacket",
    :"V-neck t-shirt",
    :"T-shirt",
    :"Shirt (tucked)",
    :"Shirt (untucked)",
    :"Hoodie",
    :"Tanktop",
    :"Baseball t-shirt",
    :"Polo Shirt",
    :"Sports top",
    :"Combat top",
    :"Combat sweater",
    :"Hooded jacket",
    :"Stealth jacket",
    :"Baggy hoodie",
    :"Battle vest",
    :"Utility vest",
    :"No shirt"
]

pants = [
    :"Fitted jeans",
    :"Skinny jeans",
    :"Jeans",
    :"Faded jeans",
    :"Work pants",
    :"Shorts",
    :"Cargo pants",
    :"Track pants",
    :"Suit pants",
    :"Slim fit suit pants",
    :"Baggy suit pants",
    :"Chinos",
    :"Sport shorts",
    :"Tropical sport shorts",
    :"Combat pants",
    :"Battle pants",
    :"Heist pants",
    :"No pants"
]

shoes = [
    :Boots,
    :Sneakers,
    :"Skate shoes",
    :"Canvas shoes",
    :"Flip-flops",
    :"Boat shoes",
    :"Running shoes",
    :"Sports shoes",
    :"Smart shoes",
    :"Sandals"
]

glasses = [
    :"Janitor Frames",
    :"Toroiseshell glasses",
    :"Professional glasses",
    :"Marble glasses",
    :"Sports glasses",
    :"Casual glasses",
    :"Aviators",
    :"Hipster glasses",
    :"High end glasses",
    :"Gun range glasses",
    :"No glasses",
    :"No glasses",
    :"No glasses",
    :"No glasses"
]

clothes = [glasses, shoes, pants, chest, head]

outfits = [
    :"The Sun Bather (Standard)",
    :"The Stoop (Standard)",
    :"The Effortless (Standard)",
    :"The Everyday (Standard)",
    :"The hoodieJock (Standard)",
    :"The Pounders Fan (Standard)",
    :"The Beat Maker (Standard)",
    :"The Brand (Standard)",
    :"The Skater (Standard)",
    :"The Roller (Standard)",
    :"The Camo Kid (Standard)",
    :"The Vibe (Standard)",
    :"The Classic TWorker (Standard)",
    :"The Rebel (Standard)",
    :"The Trendsetter (Standard)",
    :"The Artist (Standard)",
    :"The Icon (Standard)",
    :"The Nightlife (Standard)",
    :"The Mogul (Business Casual)",
    :"The Eccentric (Business Casual)",
    :"The Bulldog (Business Casual)",
    :"The Tally-Ho (Business Casual)",
    :"The European (Business Casual)",
    :"The Alligator (Business Casual)",
    :"The Victorious (Business Casual)",
    :"The Devil choice (Business Casual)",
    :"The Mr Frost (Business Casual)",
    :"The Collector (Business Casual)",
    :"The Collegiate (Business Smart)",
    :"The Egotist (Business Smart)",
    :"The Gentry (Business Smart)",
    :"The Country Club (Business Smart)",
    :"The Discotheque (Business Smart)",
    :"The Panther (Business Smart)",
    :"The Tycoon (Business Smart)",
    :"The High Roller (Business Smart)",
    :"The Yeehaw (Business Smart)",
    :"The Sophisticate (Business Smart)",
    :"The Smooth Black Suit (Open High Life)",
    :"The Smooth Gray Suit (Open High Life)",
    :"The Smooth Navy Suit (Open High Life)",
    :"The Smooth Teal Suit (Open High Life)",
    :"The Smooth Red Suit (Open High Life)",
    :"The Smooth White Suit (Open High Life)",
    :"The Smooth Brown Suit (Open High Life)",
    :"The Smooth Polar Suit (Open High Life)",
    :"The Sharp Black Suit (Open High Life)",
    :"The Sharp Gray Suit (Open High Life)",
    :"The Sharp Navy Suit (Open High Life)",
    :"The Sharp Teal Suit (Open High Life)",
    :"The Sharp Red Suit (Open High Life)",
    :"The Sharp White Suit (Open High Life)",
    :"The Sharp Brown Suit (Open High Life)",
    :"The Sharp Polar Suit (Open High Life)",
    :"The Smooth Black Suit (Closed High Life)",
    :"The Smooth Gray Suit (Closed High Life)",
    :"The Smooth Navy Suit (Closed High Life)",
    :"The Smooth Teal Suit (Closed High Life)",
    :"The Smooth Red Suit (Closed High Life)",
    :"The Smooth White Suit (Closed High Life)",
    :"The Smooth Brown Suit (Closed High Life)",
    :"The Smooth Polar Suit (Closed High Life)",
    :"The Sharp Black Suit (Closed High Life)",
    :"The Sharp Gray Suit (Closed High Life)",
    :"The Sharp Navy Suit (Closed High Life)",
    :"The Sharp Teal Suit (Closed High Life)",
    :"The Sharp Red Suit (Closed High Life)",
    :"The Sharp White Suit (Closed High Life)",
    :"The Sharp Brown Suit (Closed High Life)",
    :"The Sharp Polar Suit (Closed High Life)",
    :"The Eco (Hipster)",
    :"The Ironic (Hipster)",
    :"The Aficionado (Hipster)",
    :"The Natural (Hipster)",
    :"The Popup (Hipster)",
    :"The Artist (Hipster)",
    :"The Elitist (Hipster)",
    :"The Activist (Hipster)",
    :"The Urban Hippy (Hipster)",
    :"The Fitness (Hipster)",
    :"The Flight Suit",
    :"The Black Flight Suit",
    :"The Night (Team Heavy)",
    :"The Urban (Team Heavy)",
    :"The Steel (Team Heavy)",
    :"The Tundra (Team Heavy)",
    :"The Forest (Team Heavy)",
    :"The Night (Team Masked)",
    :"The Urban (Team Masked)",
    :"The Steel (Team Masked)",
    :"The Tundra (Team Masked)",
    :"The Forest (Team Masked)",
    :"The Night (Team)",
    :"The Urban (Team)",
    :"The Steel (Team)",
    :"The Tundra (Team)",
    :"The Forest (Team)",
    :"The Red (Heist Coveralls)",
    :"The Navy (Heist Coveralls)",
    :"The Green (Heist Coveralls)",
    :"The Gray (Heist Coveralls)",
    :"The Red Sleeved (Heist Coveralls)",
    :"The Navy Sleeved (Heist Coveralls)",
    :"The Green Sleeved (Heist Coveralls)",
    :"The Gray Sleeved (Heist Coveralls)",
    :"The Scientist (Heist Coveralls)",
    :"The Fumigator (Heist Coveralls)",
    :"The Hazard (Heist Coveralls)",
    :"The Quarantine (Heist Coveralls)",
    :"The Double (Heist Casual)",
    :"The Hoodie (Heist Casual)",
    :"The Norm (Heist Casual)",
    :"The Carefree (Heist Casual)",
    :"The Starter (Heist Street)",
    :"The Prospect (Heist Street)",
    :"The Backup (Heist Street)",
    :"The Jump-in (Heist Street)",
    :"The Drive-by (Heist Street Combat)",
    :"The Brawler (Heist Street Combat)",
    :"The Gunslinger (Heist Street Combat)",
    :"The Mercenary (Heist Street Combat)",
    :"The Skirmish (Heist Light Combat)",
    :"The Battle (Heist Light Combat)",
    :"The Conflict (Heist Light Combat)",
    :"The Fight (Heist Light Combat)",
    :"The Full Body (Heist Heavy Combat)",
    :"The Strength (Heist Heavy Combat)",
    :"The Weapon (Heist Heavy Combat)",
    :"The Command (Heist Heavy Combat)",
    :"The Tailgater (Heist Shady)",
    :"The Prowler (Heist Shady)",
    :"The Lurker (Heist Shady)",
    :"The Robber (Heist Shady)",
    :"The Geurilla (Heist Tactical Stealth)",
    :"The Raid (Heist Tactical Stealth)",
    :"The Operative (Heist Tactical Stealth)",
    :"The Pincer (Heist Tactical Stealth)",
    :"The Bravado (Heist Rebel)",
    :"The Lampadati (Heist Rebel)",
    :"The Pegassi (Heist Rebel)",
    :"The Imponte (Heist Rebel)",
    :"The Buyer (Heist Business)",
    :"The Security (Heist Business)",
    :"The Manager (Heist Business)",
    :"The Consultant (Heist Business)",
    :"The Richman (Heist Sharp)",
    :"The Portola (Heist Sharp)",
    :"The Vespucci (Heist Sharp)",
    :"The Rockford (Heist Sharp)",
    :"The Bluffs (Heist Sloppy)",
    :"The Burrito (Heist Sloppy)",
    :"The Alta (Heist Sloppy)",
    :"The Yankton (Heist Sloppy)",
    :"The Slick (Heist Minimalist)",
    :"The Fella (Heist Minimalist)",
    :"The Rogue (Heist Minimalist)",
    :"The Classic (Heist Minimalist)",
    :"The Gala (Heist Tuxedo)",
    :"The Benefit (Heist Tuxedo)",
    :"The Dinner (Heist Tuxedo)",
    :"The Ball (Heist Tuxedo)",
    :"The Burnout (Heist Rider)",
    :"The Throttle (Heist Rider)",
    :"The Metal (Heist Rider)",
    :"The Club (Heist Rider)"
]

weapons = [
    :Knife,
    :"Night Stick",
    :"AP Pistol",
    :"Combat Pistol",
    :"Pistol",
    :"Micro SMG",
    :"SMG",
    :"Assault Shotgun",
    :"Pump Shotgun",
    :"Assault SMG",
    :"Assault Rifle",
    :"Carbine Rifle",
    :"Advanced Rifle",
    :"Heavy Sniper",
    :"Sniper Rifle",
    :"MG",
    :"Combat MG",
    :"Bottle",
    :"SNS Pistol",
    :"Heavy Pistol",
    :"Special Carbine",
    :"Bullpup Rifle",
    :"Marksman Rifle",
    :"Heavy Shotgun",
    :"Vintage Pistol",
    :"Antique Cavalry Dagger"
]

challenges = [

]

GAMES[:gta_v_online] = {
    buy_link: {
        uk: 'http://www.amazon.co.uk/gp/product/B00KL4AROO/ref=as_li_tl?ie=UTF8&camp=1634&creative=19450&creativeASIN=B00KL4AROO&linkCode=as2&tag=talefromthefo-21&linkId=PDJGIANVZVI73DCC',
        us: 'http://www.amazon.com/gp/product/B00KVSQ848/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=B00KVSQ848&linkCode=as2&tag=scenargenera-20&linkId=AXYHI72GLMO6OYWG'
    },
    title: 'GTA V: Online',
    generator_title: 'Character',
    background: 'gtavonline.jpg',
    added: Date.strptime('20150424',"%Y%m%d"),
    last_updated: Date.strptime('20150424',"%Y%m%d"),
    columns: {
        car: {
            help: "Only ever drive this car. Drive a car in the same class until you can get it.",
            options: cars
        },
        car_colour: {
            help: "The exact shade is your own choice. Yeah, it's colour not color, deal with it.",
            options: car_colours
        },
        car_colour_finish: {
            options: car_colour_finishes
        },
        primary_apartment: {
            help: "Spawn point and area you prefer to hang around. If this isn't high-end you can get one as your secondary for heists.",
            options: apartments
        },
        clothes: {
            sub_trees: [ :custom, :outfit ],
            options: [
                {
                    custom: {
                        help: "You can choose the exact style within each category",
                        min: 5,
                        options: clothes
                    }
                },
                {
                    outfit: {
                        options: outfits
                    }
                }
            ]
        },
        primary_weapon: {
            help: "You may only use this weapon, except when absolutely necessary",
            options: weapons
        }
    }
}