GAMES[:pokemon] = {
    title: 'Pokemon',
    page_title: 'Pokemon Party Generator',
    save_button_message: 'Save party',
    background: 'pokemon.jpg',
    columns: {
        starter: {
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :Grass,
                :Water,
                :Fire
            ]
        },
        slot_one_type: {
            help: "This is the primary type of this pokemon. If you don't have one yet, either leave the slot open or use your starter. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Fighting',
                :'Flying',
                :'Poison',
                :'Ground',
                :'Rock',
                :'Bug',
                :'Ghost',
                :'Steel',
                :'Fire',
                :'Water',
                :'Grass',
                :'Electric',
                :'Psychic',
                :'Ice',
                :'Dragon',
                :'Dark',
                :'Fairy'
            ]
        },
        slot_two_type: {
            help: "This is the primary type of this pokemon. If you don't have one yet, either leave the slot open or use your starter. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Fighting',
                :'Flying',
                :'Poison',
                :'Ground',
                :'Rock',
                :'Bug',
                :'Ghost',
                :'Steel',
                :'Fire',
                :'Water',
                :'Grass',
                :'Electric',
                :'Psychic',
                :'Ice',
                :'Dragon',
                :'Dark',
                :'Fairy'
            ]
        },
        slot_three_type: {
            help: "This is the primary type of this pokemon. If you don't have one yet, either leave the slot open or use your starter. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Fighting',
                :'Flying',
                :'Poison',
                :'Ground',
                :'Rock',
                :'Bug',
                :'Ghost',
                :'Steel',
                :'Fire',
                :'Water',
                :'Grass',
                :'Electric',
                :'Psychic',
                :'Ice',
                :'Dragon',
                :'Dark',
                :'Fairy'
            ]
        },
        slot_four_type: {
            help: "This is the primary type of this pokemon. If you don't have one yet, either leave the slot open or use your starter. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Fighting',
                :'Flying',
                :'Poison',
                :'Ground',
                :'Rock',
                :'Bug',
                :'Ghost',
                :'Steel',
                :'Fire',
                :'Water',
                :'Grass',
                :'Electric',
                :'Psychic',
                :'Ice',
                :'Dragon',
                :'Dark',
                :'Fairy'
            ]
        },
        slot_five_type: {
            help: "This is the primary type of this pokemon, you can use dual-types. If you don't have one yet, either leave the slot open or use your starter. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Fighting',
                :'Flying',
                :'Poison',
                :'Ground',
                :'Rock',
                :'Bug',
                :'Ghost',
                :'Steel',
                :'Fire',
                :'Water',
                :'Grass',
                :'Electric',
                :'Psychic',
                :'Ice',
                :'Dragon',
                :'Dark',
                :'Fairy'
            ]
        },
        slot_six_type: {
            help: "This is the primary type of this pokemon. If you don't have one yet, either leave the slot open or use your starter. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Fighting',
                :'Flying',
                :'Poison',
                :'Ground',
                :'Rock',
                :'Bug',
                :'Ghost',
                :'Steel',
                :'Fire',
                :'Water',
                :'Grass',
                :'Electric',
                :'Psychic',
                :'Ice',
                :'Dragon',
                :'Dark',
                :'Fairy'
            ]
        }
    } 
}