GAMES[:pokemon] = {
    title: 'Pokemon',
    page_title: 'Pokemon Party Generator',
    save_button_message: 'Save party',
    background: 'pokemon.jpg',
    columns: {
        starter: {
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :Grass,
                :Water,
                :Fire
            ]
        },
        slot_one_type: {
            help: "If you don't have a Pokemon of a given type, use one of it's subtypes. If you can't do that, or it is a single type, leave the slot open or use your starter until you do. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Normal Fighting',
                :'Normal Flying',
                :'Normal Poison',
                :'Normal Ground',
                :'Normal Rock',
                :'Normal Bug',
                :'Normal Ghost',
                :'Normal Steel',
                :'Normal Fire',
                :'Normal Water',
                :'Normal Grass',
                :'Normal Electric',
                :'Normal Psychic',
                :'Normal Ice',
                :'Normal Dragon',
                :'Normal Dark',
                :'Normal Fairy',
                :'Fighting',
                :'Fighting Flying',
                :'Fighting Poison',
                :'Fighting Ground',
                :'Fighting Rock',
                :'Fighting Bug',
                :'Fighting Ghost',
                :'Fighting Steel',
                :'Fighting Fire',
                :'Fighting Water',
                :'Fighting Grass',
                :'Fighting Electric',
                :'Fighting Psychic',
                :'Fighting Ice',
                :'Fighting Dragon',
                :'Fighting Dark',
                :'Fighting Fairy',
                :'Flying',
                :'Flying Poison',
                :'Flying Ground',
                :'Flying Rock',
                :'Flying Bug',
                :'Flying Ghost',
                :'Flying Steel',
                :'Flying Fire',
                :'Flying Water',
                :'Flying Grass',
                :'Flying Electric',
                :'Flying Psychic',
                :'Flying Ice',
                :'Flying Dragon',
                :'Flying Dark',
                :'Flying Fairy',
                :'Poison',
                :'Poison Ground',
                :'Poison Rock',
                :'Poison Bug',
                :'Poison Ghost',
                :'Poison Steel',
                :'Poison Fire',
                :'Poison Water',
                :'Poison Grass',
                :'Poison Electric',
                :'Poison Psychic',
                :'Poison Ice',
                :'Poison Dragon',
                :'Poison Dark',
                :'Poison Fairy',
                :'Ground',
                :'Ground Rock',
                :'Ground Bug',
                :'Ground Ghost',
                :'Ground Steel',
                :'Ground Fire',
                :'Ground Water',
                :'Ground Grass',
                :'Ground Electric',
                :'Ground Psychic',
                :'Ground Ice',
                :'Ground Dragon',
                :'Ground Dark',
                :'Ground Fairy',
                :'Rock',
                :'Rock Bug',
                :'Rock Ghost',
                :'Rock Steel',
                :'Rock Fire',
                :'Rock Water',
                :'Rock Grass',
                :'Rock Electric',
                :'Rock Psychic',
                :'Rock Ice',
                :'Rock Dragon',
                :'Rock Dark',
                :'Rock Fairy',
                :'Bug',
                :'Bug Ghost',
                :'Bug Steel',
                :'Bug Fire',
                :'Bug Water',
                :'Bug Grass',
                :'Bug Electric',
                :'Bug Psychic',
                :'Bug Ice',
                :'Bug Dragon',
                :'Bug Dark',
                :'Bug Fairy',
                :'Ghost',
                :'Ghost Steel',
                :'Ghost Fire',
                :'Ghost Water',
                :'Ghost Grass',
                :'Ghost Electric',
                :'Ghost Psychic',
                :'Ghost Ice',
                :'Ghost Dragon',
                :'Ghost Dark',
                :'Ghost Fairy',
                :'Steel',
                :'Steel Fire',
                :'Steel Water',
                :'Steel Grass',
                :'Steel Electric',
                :'Steel Psychic',
                :'Steel Ice',
                :'Steel Dragon',
                :'Steel Dark',
                :'Steel Fairy',
                :'Fire',
                :'Fire Water',
                :'Fire Grass',
                :'Fire Electric',
                :'Fire Psychic',
                :'Fire Ice',
                :'Fire Dragon',
                :'Fire Dark',
                :'Fire Fairy',
                :'Water',
                :'Water Grass',
                :'Water Electric',
                :'Water Psychic',
                :'Water Ice',
                :'Water Dragon',
                :'Water Dark',
                :'Water Fairy',
                :'Grass',
                :'Grass Electric',
                :'Grass Psychic',
                :'Grass Ice',
                :'Grass Dragon',
                :'Grass Dark',
                :'Grass Fairy',
                :'Electric 6',
                :'Electric Psychic',
                :'Electric Ice',
                :'Electric Dragon',
                :'Electric Dark',
                :'Electric Fairy',
                :'Psychic',
                :'Psychic Ice',
                :'Psychic Dragon',
                :'Psychic Dark',
                :'Psychic Fairy',
                :'Ice',
                :'Ice Dragon',
                :'Ice Dark',
                :'Ice Fairy',
                :'Dragon',
                :'Dragon Dark',
                :'Dragon Fairy',
                :'Dark',
                :'Dark Fairy',
                :'Fairy'
            ]
        },
        slot_two_type: {
            help: "If you don't have a Pokemon of a given type, use one of it's subtypes. If you can't do that, or it is a single type, leave the slot open or use your starter until you do. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Normal Fighting',
                :'Normal Flying',
                :'Normal Poison',
                :'Normal Ground',
                :'Normal Rock',
                :'Normal Bug',
                :'Normal Ghost',
                :'Normal Steel',
                :'Normal Fire',
                :'Normal Water',
                :'Normal Grass',
                :'Normal Electric',
                :'Normal Psychic',
                :'Normal Ice',
                :'Normal Dragon',
                :'Normal Dark',
                :'Normal Fairy',
                :'Fighting',
                :'Fighting Flying',
                :'Fighting Poison',
                :'Fighting Ground',
                :'Fighting Rock',
                :'Fighting Bug',
                :'Fighting Ghost',
                :'Fighting Steel',
                :'Fighting Fire',
                :'Fighting Water',
                :'Fighting Grass',
                :'Fighting Electric',
                :'Fighting Psychic',
                :'Fighting Ice',
                :'Fighting Dragon',
                :'Fighting Dark',
                :'Fighting Fairy',
                :'Flying',
                :'Flying Poison',
                :'Flying Ground',
                :'Flying Rock',
                :'Flying Bug',
                :'Flying Ghost',
                :'Flying Steel',
                :'Flying Fire',
                :'Flying Water',
                :'Flying Grass',
                :'Flying Electric',
                :'Flying Psychic',
                :'Flying Ice',
                :'Flying Dragon',
                :'Flying Dark',
                :'Flying Fairy',
                :'Poison',
                :'Poison Ground',
                :'Poison Rock',
                :'Poison Bug',
                :'Poison Ghost',
                :'Poison Steel',
                :'Poison Fire',
                :'Poison Water',
                :'Poison Grass',
                :'Poison Electric',
                :'Poison Psychic',
                :'Poison Ice',
                :'Poison Dragon',
                :'Poison Dark',
                :'Poison Fairy',
                :'Ground',
                :'Ground Rock',
                :'Ground Bug',
                :'Ground Ghost',
                :'Ground Steel',
                :'Ground Fire',
                :'Ground Water',
                :'Ground Grass',
                :'Ground Electric',
                :'Ground Psychic',
                :'Ground Ice',
                :'Ground Dragon',
                :'Ground Dark',
                :'Ground Fairy',
                :'Rock',
                :'Rock Bug',
                :'Rock Ghost',
                :'Rock Steel',
                :'Rock Fire',
                :'Rock Water',
                :'Rock Grass',
                :'Rock Electric',
                :'Rock Psychic',
                :'Rock Ice',
                :'Rock Dragon',
                :'Rock Dark',
                :'Rock Fairy',
                :'Bug',
                :'Bug Ghost',
                :'Bug Steel',
                :'Bug Fire',
                :'Bug Water',
                :'Bug Grass',
                :'Bug Electric',
                :'Bug Psychic',
                :'Bug Ice',
                :'Bug Dragon',
                :'Bug Dark',
                :'Bug Fairy',
                :'Ghost',
                :'Ghost Steel',
                :'Ghost Fire',
                :'Ghost Water',
                :'Ghost Grass',
                :'Ghost Electric',
                :'Ghost Psychic',
                :'Ghost Ice',
                :'Ghost Dragon',
                :'Ghost Dark',
                :'Ghost Fairy',
                :'Steel',
                :'Steel Fire',
                :'Steel Water',
                :'Steel Grass',
                :'Steel Electric',
                :'Steel Psychic',
                :'Steel Ice',
                :'Steel Dragon',
                :'Steel Dark',
                :'Steel Fairy',
                :'Fire',
                :'Fire Water',
                :'Fire Grass',
                :'Fire Electric',
                :'Fire Psychic',
                :'Fire Ice',
                :'Fire Dragon',
                :'Fire Dark',
                :'Fire Fairy',
                :'Water',
                :'Water Grass',
                :'Water Electric',
                :'Water Psychic',
                :'Water Ice',
                :'Water Dragon',
                :'Water Dark',
                :'Water Fairy',
                :'Grass',
                :'Grass Electric',
                :'Grass Psychic',
                :'Grass Ice',
                :'Grass Dragon',
                :'Grass Dark',
                :'Grass Fairy',
                :'Electric 6',
                :'Electric Psychic',
                :'Electric Ice',
                :'Electric Dragon',
                :'Electric Dark',
                :'Electric Fairy',
                :'Psychic',
                :'Psychic Ice',
                :'Psychic Dragon',
                :'Psychic Dark',
                :'Psychic Fairy',
                :'Ice',
                :'Ice Dragon',
                :'Ice Dark',
                :'Ice Fairy',
                :'Dragon',
                :'Dragon Dark',
                :'Dragon Fairy',
                :'Dark',
                :'Dark Fairy',
                :'Fairy'
            ]
        },
        slot_three_type: {
            help: "If you don't have a Pokemon of a given type, use one of it's subtypes. If you can't do that, or it is a single type, leave the slot open or use your starter until you do. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Normal Fighting',
                :'Normal Flying',
                :'Normal Poison',
                :'Normal Ground',
                :'Normal Rock',
                :'Normal Bug',
                :'Normal Ghost',
                :'Normal Steel',
                :'Normal Fire',
                :'Normal Water',
                :'Normal Grass',
                :'Normal Electric',
                :'Normal Psychic',
                :'Normal Ice',
                :'Normal Dragon',
                :'Normal Dark',
                :'Normal Fairy',
                :'Fighting',
                :'Fighting Flying',
                :'Fighting Poison',
                :'Fighting Ground',
                :'Fighting Rock',
                :'Fighting Bug',
                :'Fighting Ghost',
                :'Fighting Steel',
                :'Fighting Fire',
                :'Fighting Water',
                :'Fighting Grass',
                :'Fighting Electric',
                :'Fighting Psychic',
                :'Fighting Ice',
                :'Fighting Dragon',
                :'Fighting Dark',
                :'Fighting Fairy',
                :'Flying',
                :'Flying Poison',
                :'Flying Ground',
                :'Flying Rock',
                :'Flying Bug',
                :'Flying Ghost',
                :'Flying Steel',
                :'Flying Fire',
                :'Flying Water',
                :'Flying Grass',
                :'Flying Electric',
                :'Flying Psychic',
                :'Flying Ice',
                :'Flying Dragon',
                :'Flying Dark',
                :'Flying Fairy',
                :'Poison',
                :'Poison Ground',
                :'Poison Rock',
                :'Poison Bug',
                :'Poison Ghost',
                :'Poison Steel',
                :'Poison Fire',
                :'Poison Water',
                :'Poison Grass',
                :'Poison Electric',
                :'Poison Psychic',
                :'Poison Ice',
                :'Poison Dragon',
                :'Poison Dark',
                :'Poison Fairy',
                :'Ground',
                :'Ground Rock',
                :'Ground Bug',
                :'Ground Ghost',
                :'Ground Steel',
                :'Ground Fire',
                :'Ground Water',
                :'Ground Grass',
                :'Ground Electric',
                :'Ground Psychic',
                :'Ground Ice',
                :'Ground Dragon',
                :'Ground Dark',
                :'Ground Fairy',
                :'Rock',
                :'Rock Bug',
                :'Rock Ghost',
                :'Rock Steel',
                :'Rock Fire',
                :'Rock Water',
                :'Rock Grass',
                :'Rock Electric',
                :'Rock Psychic',
                :'Rock Ice',
                :'Rock Dragon',
                :'Rock Dark',
                :'Rock Fairy',
                :'Bug',
                :'Bug Ghost',
                :'Bug Steel',
                :'Bug Fire',
                :'Bug Water',
                :'Bug Grass',
                :'Bug Electric',
                :'Bug Psychic',
                :'Bug Ice',
                :'Bug Dragon',
                :'Bug Dark',
                :'Bug Fairy',
                :'Ghost',
                :'Ghost Steel',
                :'Ghost Fire',
                :'Ghost Water',
                :'Ghost Grass',
                :'Ghost Electric',
                :'Ghost Psychic',
                :'Ghost Ice',
                :'Ghost Dragon',
                :'Ghost Dark',
                :'Ghost Fairy',
                :'Steel',
                :'Steel Fire',
                :'Steel Water',
                :'Steel Grass',
                :'Steel Electric',
                :'Steel Psychic',
                :'Steel Ice',
                :'Steel Dragon',
                :'Steel Dark',
                :'Steel Fairy',
                :'Fire',
                :'Fire Water',
                :'Fire Grass',
                :'Fire Electric',
                :'Fire Psychic',
                :'Fire Ice',
                :'Fire Dragon',
                :'Fire Dark',
                :'Fire Fairy',
                :'Water',
                :'Water Grass',
                :'Water Electric',
                :'Water Psychic',
                :'Water Ice',
                :'Water Dragon',
                :'Water Dark',
                :'Water Fairy',
                :'Grass',
                :'Grass Electric',
                :'Grass Psychic',
                :'Grass Ice',
                :'Grass Dragon',
                :'Grass Dark',
                :'Grass Fairy',
                :'Electric 6',
                :'Electric Psychic',
                :'Electric Ice',
                :'Electric Dragon',
                :'Electric Dark',
                :'Electric Fairy',
                :'Psychic',
                :'Psychic Ice',
                :'Psychic Dragon',
                :'Psychic Dark',
                :'Psychic Fairy',
                :'Ice',
                :'Ice Dragon',
                :'Ice Dark',
                :'Ice Fairy',
                :'Dragon',
                :'Dragon Dark',
                :'Dragon Fairy',
                :'Dark',
                :'Dark Fairy',
                :'Fairy'
            ]
        },
        slot_four_type: {
            help: "If you don't have a Pokemon of a given type, use one of it's subtypes. If you can't do that, or it is a single type, leave the slot open or use your starter until you do. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Normal Fighting',
                :'Normal Flying',
                :'Normal Poison',
                :'Normal Ground',
                :'Normal Rock',
                :'Normal Bug',
                :'Normal Ghost',
                :'Normal Steel',
                :'Normal Fire',
                :'Normal Water',
                :'Normal Grass',
                :'Normal Electric',
                :'Normal Psychic',
                :'Normal Ice',
                :'Normal Dragon',
                :'Normal Dark',
                :'Normal Fairy',
                :'Fighting',
                :'Fighting Flying',
                :'Fighting Poison',
                :'Fighting Ground',
                :'Fighting Rock',
                :'Fighting Bug',
                :'Fighting Ghost',
                :'Fighting Steel',
                :'Fighting Fire',
                :'Fighting Water',
                :'Fighting Grass',
                :'Fighting Electric',
                :'Fighting Psychic',
                :'Fighting Ice',
                :'Fighting Dragon',
                :'Fighting Dark',
                :'Fighting Fairy',
                :'Flying',
                :'Flying Poison',
                :'Flying Ground',
                :'Flying Rock',
                :'Flying Bug',
                :'Flying Ghost',
                :'Flying Steel',
                :'Flying Fire',
                :'Flying Water',
                :'Flying Grass',
                :'Flying Electric',
                :'Flying Psychic',
                :'Flying Ice',
                :'Flying Dragon',
                :'Flying Dark',
                :'Flying Fairy',
                :'Poison',
                :'Poison Ground',
                :'Poison Rock',
                :'Poison Bug',
                :'Poison Ghost',
                :'Poison Steel',
                :'Poison Fire',
                :'Poison Water',
                :'Poison Grass',
                :'Poison Electric',
                :'Poison Psychic',
                :'Poison Ice',
                :'Poison Dragon',
                :'Poison Dark',
                :'Poison Fairy',
                :'Ground',
                :'Ground Rock',
                :'Ground Bug',
                :'Ground Ghost',
                :'Ground Steel',
                :'Ground Fire',
                :'Ground Water',
                :'Ground Grass',
                :'Ground Electric',
                :'Ground Psychic',
                :'Ground Ice',
                :'Ground Dragon',
                :'Ground Dark',
                :'Ground Fairy',
                :'Rock',
                :'Rock Bug',
                :'Rock Ghost',
                :'Rock Steel',
                :'Rock Fire',
                :'Rock Water',
                :'Rock Grass',
                :'Rock Electric',
                :'Rock Psychic',
                :'Rock Ice',
                :'Rock Dragon',
                :'Rock Dark',
                :'Rock Fairy',
                :'Bug',
                :'Bug Ghost',
                :'Bug Steel',
                :'Bug Fire',
                :'Bug Water',
                :'Bug Grass',
                :'Bug Electric',
                :'Bug Psychic',
                :'Bug Ice',
                :'Bug Dragon',
                :'Bug Dark',
                :'Bug Fairy',
                :'Ghost',
                :'Ghost Steel',
                :'Ghost Fire',
                :'Ghost Water',
                :'Ghost Grass',
                :'Ghost Electric',
                :'Ghost Psychic',
                :'Ghost Ice',
                :'Ghost Dragon',
                :'Ghost Dark',
                :'Ghost Fairy',
                :'Steel',
                :'Steel Fire',
                :'Steel Water',
                :'Steel Grass',
                :'Steel Electric',
                :'Steel Psychic',
                :'Steel Ice',
                :'Steel Dragon',
                :'Steel Dark',
                :'Steel Fairy',
                :'Fire',
                :'Fire Water',
                :'Fire Grass',
                :'Fire Electric',
                :'Fire Psychic',
                :'Fire Ice',
                :'Fire Dragon',
                :'Fire Dark',
                :'Fire Fairy',
                :'Water',
                :'Water Grass',
                :'Water Electric',
                :'Water Psychic',
                :'Water Ice',
                :'Water Dragon',
                :'Water Dark',
                :'Water Fairy',
                :'Grass',
                :'Grass Electric',
                :'Grass Psychic',
                :'Grass Ice',
                :'Grass Dragon',
                :'Grass Dark',
                :'Grass Fairy',
                :'Electric 6',
                :'Electric Psychic',
                :'Electric Ice',
                :'Electric Dragon',
                :'Electric Dark',
                :'Electric Fairy',
                :'Psychic',
                :'Psychic Ice',
                :'Psychic Dragon',
                :'Psychic Dark',
                :'Psychic Fairy',
                :'Ice',
                :'Ice Dragon',
                :'Ice Dark',
                :'Ice Fairy',
                :'Dragon',
                :'Dragon Dark',
                :'Dragon Fairy',
                :'Dark',
                :'Dark Fairy',
                :'Fairy'
            ]
        },
        slot_five_type: {
            help: "If you don't have a Pokemon of a given type, use one of it's subtypes. If you can't do that, or it is a single type, leave the slot open or use your starter until you do. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Normal Fighting',
                :'Normal Flying',
                :'Normal Poison',
                :'Normal Ground',
                :'Normal Rock',
                :'Normal Bug',
                :'Normal Ghost',
                :'Normal Steel',
                :'Normal Fire',
                :'Normal Water',
                :'Normal Grass',
                :'Normal Electric',
                :'Normal Psychic',
                :'Normal Ice',
                :'Normal Dragon',
                :'Normal Dark',
                :'Normal Fairy',
                :'Fighting',
                :'Fighting Flying',
                :'Fighting Poison',
                :'Fighting Ground',
                :'Fighting Rock',
                :'Fighting Bug',
                :'Fighting Ghost',
                :'Fighting Steel',
                :'Fighting Fire',
                :'Fighting Water',
                :'Fighting Grass',
                :'Fighting Electric',
                :'Fighting Psychic',
                :'Fighting Ice',
                :'Fighting Dragon',
                :'Fighting Dark',
                :'Fighting Fairy',
                :'Flying',
                :'Flying Poison',
                :'Flying Ground',
                :'Flying Rock',
                :'Flying Bug',
                :'Flying Ghost',
                :'Flying Steel',
                :'Flying Fire',
                :'Flying Water',
                :'Flying Grass',
                :'Flying Electric',
                :'Flying Psychic',
                :'Flying Ice',
                :'Flying Dragon',
                :'Flying Dark',
                :'Flying Fairy',
                :'Poison',
                :'Poison Ground',
                :'Poison Rock',
                :'Poison Bug',
                :'Poison Ghost',
                :'Poison Steel',
                :'Poison Fire',
                :'Poison Water',
                :'Poison Grass',
                :'Poison Electric',
                :'Poison Psychic',
                :'Poison Ice',
                :'Poison Dragon',
                :'Poison Dark',
                :'Poison Fairy',
                :'Ground',
                :'Ground Rock',
                :'Ground Bug',
                :'Ground Ghost',
                :'Ground Steel',
                :'Ground Fire',
                :'Ground Water',
                :'Ground Grass',
                :'Ground Electric',
                :'Ground Psychic',
                :'Ground Ice',
                :'Ground Dragon',
                :'Ground Dark',
                :'Ground Fairy',
                :'Rock',
                :'Rock Bug',
                :'Rock Ghost',
                :'Rock Steel',
                :'Rock Fire',
                :'Rock Water',
                :'Rock Grass',
                :'Rock Electric',
                :'Rock Psychic',
                :'Rock Ice',
                :'Rock Dragon',
                :'Rock Dark',
                :'Rock Fairy',
                :'Bug',
                :'Bug Ghost',
                :'Bug Steel',
                :'Bug Fire',
                :'Bug Water',
                :'Bug Grass',
                :'Bug Electric',
                :'Bug Psychic',
                :'Bug Ice',
                :'Bug Dragon',
                :'Bug Dark',
                :'Bug Fairy',
                :'Ghost',
                :'Ghost Steel',
                :'Ghost Fire',
                :'Ghost Water',
                :'Ghost Grass',
                :'Ghost Electric',
                :'Ghost Psychic',
                :'Ghost Ice',
                :'Ghost Dragon',
                :'Ghost Dark',
                :'Ghost Fairy',
                :'Steel',
                :'Steel Fire',
                :'Steel Water',
                :'Steel Grass',
                :'Steel Electric',
                :'Steel Psychic',
                :'Steel Ice',
                :'Steel Dragon',
                :'Steel Dark',
                :'Steel Fairy',
                :'Fire',
                :'Fire Water',
                :'Fire Grass',
                :'Fire Electric',
                :'Fire Psychic',
                :'Fire Ice',
                :'Fire Dragon',
                :'Fire Dark',
                :'Fire Fairy',
                :'Water',
                :'Water Grass',
                :'Water Electric',
                :'Water Psychic',
                :'Water Ice',
                :'Water Dragon',
                :'Water Dark',
                :'Water Fairy',
                :'Grass',
                :'Grass Electric',
                :'Grass Psychic',
                :'Grass Ice',
                :'Grass Dragon',
                :'Grass Dark',
                :'Grass Fairy',
                :'Electric 6',
                :'Electric Psychic',
                :'Electric Ice',
                :'Electric Dragon',
                :'Electric Dark',
                :'Electric Fairy',
                :'Psychic',
                :'Psychic Ice',
                :'Psychic Dragon',
                :'Psychic Dark',
                :'Psychic Fairy',
                :'Ice',
                :'Ice Dragon',
                :'Ice Dark',
                :'Ice Fairy',
                :'Dragon',
                :'Dragon Dark',
                :'Dragon Fairy',
                :'Dark',
                :'Dark Fairy',
                :'Fairy'
            ]
        },
        slot_six_type: {
            help: "If you don't have a Pokemon of a given type, use one of it's subtypes. If you can't do that, or it is a single type, leave the slot open or use your starter until you do. If your game does not have this type, reroll.",
            chance_of_multiple: 0,
            min: 1,
            max: 1,
            options: [
                :'Normal',
                :'Normal Fighting',
                :'Normal Flying',
                :'Normal Poison',
                :'Normal Ground',
                :'Normal Rock',
                :'Normal Bug',
                :'Normal Ghost',
                :'Normal Steel',
                :'Normal Fire',
                :'Normal Water',
                :'Normal Grass',
                :'Normal Electric',
                :'Normal Psychic',
                :'Normal Ice',
                :'Normal Dragon',
                :'Normal Dark',
                :'Normal Fairy',
                :'Fighting',
                :'Fighting Flying',
                :'Fighting Poison',
                :'Fighting Ground',
                :'Fighting Rock',
                :'Fighting Bug',
                :'Fighting Ghost',
                :'Fighting Steel',
                :'Fighting Fire',
                :'Fighting Water',
                :'Fighting Grass',
                :'Fighting Electric',
                :'Fighting Psychic',
                :'Fighting Ice',
                :'Fighting Dragon',
                :'Fighting Dark',
                :'Fighting Fairy',
                :'Flying',
                :'Flying Poison',
                :'Flying Ground',
                :'Flying Rock',
                :'Flying Bug',
                :'Flying Ghost',
                :'Flying Steel',
                :'Flying Fire',
                :'Flying Water',
                :'Flying Grass',
                :'Flying Electric',
                :'Flying Psychic',
                :'Flying Ice',
                :'Flying Dragon',
                :'Flying Dark',
                :'Flying Fairy',
                :'Poison',
                :'Poison Ground',
                :'Poison Rock',
                :'Poison Bug',
                :'Poison Ghost',
                :'Poison Steel',
                :'Poison Fire',
                :'Poison Water',
                :'Poison Grass',
                :'Poison Electric',
                :'Poison Psychic',
                :'Poison Ice',
                :'Poison Dragon',
                :'Poison Dark',
                :'Poison Fairy',
                :'Ground',
                :'Ground Rock',
                :'Ground Bug',
                :'Ground Ghost',
                :'Ground Steel',
                :'Ground Fire',
                :'Ground Water',
                :'Ground Grass',
                :'Ground Electric',
                :'Ground Psychic',
                :'Ground Ice',
                :'Ground Dragon',
                :'Ground Dark',
                :'Ground Fairy',
                :'Rock',
                :'Rock Bug',
                :'Rock Ghost',
                :'Rock Steel',
                :'Rock Fire',
                :'Rock Water',
                :'Rock Grass',
                :'Rock Electric',
                :'Rock Psychic',
                :'Rock Ice',
                :'Rock Dragon',
                :'Rock Dark',
                :'Rock Fairy',
                :'Bug',
                :'Bug Ghost',
                :'Bug Steel',
                :'Bug Fire',
                :'Bug Water',
                :'Bug Grass',
                :'Bug Electric',
                :'Bug Psychic',
                :'Bug Ice',
                :'Bug Dragon',
                :'Bug Dark',
                :'Bug Fairy',
                :'Ghost',
                :'Ghost Steel',
                :'Ghost Fire',
                :'Ghost Water',
                :'Ghost Grass',
                :'Ghost Electric',
                :'Ghost Psychic',
                :'Ghost Ice',
                :'Ghost Dragon',
                :'Ghost Dark',
                :'Ghost Fairy',
                :'Steel',
                :'Steel Fire',
                :'Steel Water',
                :'Steel Grass',
                :'Steel Electric',
                :'Steel Psychic',
                :'Steel Ice',
                :'Steel Dragon',
                :'Steel Dark',
                :'Steel Fairy',
                :'Fire',
                :'Fire Water',
                :'Fire Grass',
                :'Fire Electric',
                :'Fire Psychic',
                :'Fire Ice',
                :'Fire Dragon',
                :'Fire Dark',
                :'Fire Fairy',
                :'Water',
                :'Water Grass',
                :'Water Electric',
                :'Water Psychic',
                :'Water Ice',
                :'Water Dragon',
                :'Water Dark',
                :'Water Fairy',
                :'Grass',
                :'Grass Electric',
                :'Grass Psychic',
                :'Grass Ice',
                :'Grass Dragon',
                :'Grass Dark',
                :'Grass Fairy',
                :'Electric 6',
                :'Electric Psychic',
                :'Electric Ice',
                :'Electric Dragon',
                :'Electric Dark',
                :'Electric Fairy',
                :'Psychic',
                :'Psychic Ice',
                :'Psychic Dragon',
                :'Psychic Dark',
                :'Psychic Fairy',
                :'Ice',
                :'Ice Dragon',
                :'Ice Dark',
                :'Ice Fairy',
                :'Dragon',
                :'Dragon Dark',
                :'Dragon Fairy',
                :'Dark',
                :'Dark Fairy',
                :'Fairy'
            ]
        }
    } 
}